# ArgoCD Project for Backend Team
# Implements tenant isolation with restricted access
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-backend
  namespace: argocd
spec:
  description: Backend team project with restricted access
  
  # Allowed source repositories
  sourceRepos:
  - https://github.com/CodeWithPraveen/ps-scaling-gitops-tmp
  
  # Allowed destination clusters and namespaces
  # Matches the namespaces created by the ApplicationSet (globomantics-*)
  destinations:
  - namespace: 'globomantics-*'
    server: '*'
  
  # Deny all cluster-scoped resources
  clusterResourceWhitelist: []
  
  # Allow only specific namespace-scoped resources
  namespaceResourceWhitelist:
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: Secret
  - group: ''
    kind: Service
  - group: apps
    kind: Deployment
  - group: apps
    kind: StatefulSet
  - group: networking.k8s.io
    kind: Ingress
  
  # Roles for team members
  roles:
  - name: developer
    description: Developer read and sync access
    policies:
    - p, proj:team-backend:developer, applications, get, team-backend/*, allow
    - p, proj:team-backend:developer, applications, sync, team-backend/*, allow
    groups:
    - backend-developers # Refers to SSO/LDAP group
  - name: admin
    description: Full admin access for team leads
    policies:
    - p, proj:team-backend:admin, applications, *, team-backend/*, allow
    groups:
    - backend-admins # Refers to SSO/LDAP group
