apiVersion: constraints.gatekeeper.sh/v1beta1
kind: TeamIsolation                      # Uses CRD from ConstraintTemplate
metadata:
  name: team-backend-isolation
spec:
  match:                                 # Which resources to validate
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
    namespaces:                          # Which namespaces
      - globomantics-development
      - globomantics-staging
      - globomantics-production
  parameters:
    allowedTeams:                        # Parameters for the policy
      - team-backend                     # Only backend team allowed in this namespace
