# Database Credentials Secret
# NOTE: In production, use external secret managers (Vault, AWS Secrets Manager, etc.)
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  labels:
    app: migrations-demo
type: Opaque
stringData:
  username: postgres
  password: postgres123
  url: jdbc:postgresql://postgres-service.globomantics:5432/globomantics
