# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: postgres
    tier: data
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: postgres
