# API Gateway - Deploys after database (sync-wave: 2)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: globomantics-api-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/CodeWithPraveen/ps-scaling-gitops
    path: applications/ecommerce/services/api-gateway
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: globomantics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
