# Database Service - Deploys first (sync-wave: 1)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: globomantics-database
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/CodeWithPraveen/ps-scaling-gitops-tmp
    path: applications/ecommerce/services/database
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: globomantics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
