# ArgoCD Application using OCI Helm chart
# References Helm chart stored in OCI registry
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-from-oci
  namespace: argocd
spec:
  project: default
  source:
    repoURL: globomantics.azurecr.io/helm
    chart: globomantics-backend
    targetRevision: 2.1.0
    helm:
      releaseName: backend-api
      values: |
        replicaCount: 3
        image:
          repository: globomantics.azurecr.io/backend-api
          tag: v2.1.0
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: 500m
  destination:
    server: https://kubernetes.default.svc
    namespace: globomantics
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
