# App-of-Apps pattern for Globomantics E-commerce
# Single Application that manages all microservices
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: globomantics-ecommerce
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/CodeWithPraveen/ps-scaling-gitops
    path: applications/ecommerce/applications
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
